######
# See: https://hub.docker.com/_/php/
######

FROM php:7.4-fpm
#ENVREFRESH_DATE 2020-08-11 18:43:20
######
# You can install php extensions using docker-php-ext-install
######

#ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/

#RUN chmod uga+x /usr/local/bin/install-php-extensions && sync && install-php-extensions gd xdebug

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak \
    && echo 'deb http://mirrors.aliyun.com/debian/ buster main non-free contrib' > /etc/apt/sources.list \
    && echo 'deb http://mirrors.aliyun.com/debian-security buster/updates main' >> /etc/apt/sources.list \
    && echo 'deb http://mirrors.aliyun.com/debian/ buster-updates main non-free contrib' >> /etc/apt/sources.list \
    && echo 'deb http://mirrors.aliyun.com/debian/ buster-backports main non-free contrib' >> /etc/apt/sources.list \
    #&& echo 'deb http://mirrors.163.com/debian/ stretch main non-free contrib' > /etc/apt/sources.list \
    #&& echo 'deb http://mirrors.163.com/debian/ stretch-updates main non-free contrib' >> /etc/apt/sources.list \
    #&& echo 'deb http://mirrors.163.com/debian-security/ stretch/updates main non-free contrib' >> /etc/apt/sources.list \
    && apt-get update

RUN pecl list-channels && pecl update-channels 
# && pecl list-all

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/

#RUN chmod uga+x /usr/local/bin/install-php-extensions && sync && \

RUN install-php-extensions xdebug memcached memcache mongodb mcrypt yaml \
           solr xhprof gd pdo_mysql pdo_pgsql pgsql intl \
           redis opcache bcmath swoole zip imagick

RUN apt-get update\
    && export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
    && apt-get autoremove 

RUN apt-get remove libssl1.0-dev libxml2-dev libzstd-dev zlib1g-dev

RUN apt-get autoremove && apt-get autoclean 

RUN apt-get install -y --fix-missing  nginx\
        apt-utils vim \
       --no-install-recommends libfreetype6-dev libjpeg62-turbo-dev \
#       libmagickwand-dev libmcrypt-dev  zlib1g-dev \
#       libjpeg-dev libwmf-dev libx11-dev libxext-dev libtiff-dev libbz2-dev libwebp-dev \
#       libsasl2-dev \
#       libssl-dev \
#       libpng-dev \
#       libjpeg-dev \
#       libpq-dev \
#       libcurl4-gnutls-dev \
#       libicu-dev \
#       libxml2-dev \
#       libpq-dev \
#       zlib1g-dev \
#       libmemcached-dev \
       git \
       g++ \
       && rm -rf /var/lib/apt/lists/* \
   # && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
   # && docker-php-ext-install -j$(nproc) gd \
   # && pecl list-channels && pecl update-channels && pecl list-all \
   # && pecl install imagick-3.4.4 mcrypt-1.0.2 memcached-3.1.3 redis-5.0.2 xdebug-2.7.2 swoole-4.4.3\
   # && docker-php-ext-enable imagick mcrypt memcached redis xdebug swoole \
   # && docker-php-ext-configure opcache --enable-opcache && docker-php-ext-install opcache \
    && apt-get autoremove && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/pear

RUN echo "Asia/ShangHai" > /etc/timezone; dpkg-reconfigure -f noninteractive tzdata
RUN mkdir -p /home/wwwlogs
RUN chmod 777 -R /etc/nginx/conf.d
RUN chmod 777 -R /home/wwwlogs
RUN mkdir -p /www/web/self_php
# 生成 php.ini 配置
# WORKDIR /usr/share/nginx/html
WORKDIR /www/web/self_php/
COPY ./init.sh /
RUN /bin/sh /init.sh

CMD ["nginx"]
CMD ["php-fpm"]


