version: '2.2'
services:
  kibana:
    image: kibana:7.5.2
    container_name: kibana
    environment:
    - I18N_LOCALE=zh-CN
    - XPACK_GRAPH_ENABLED=true
    - TIMELION_ENABLED=true
    - XPACK_MONITORING_COLLECTION_ENABLED="true"
    - ELASTICSEARCH_URL=http://192.168.144.3:9200
    - ELASTICSEARCH_URL=http://192.168.144.2:9200
    - ELASTICSEARCH_URL=http://192.168.144.4:9200
    volumes:
      - ./config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - kibana
    restart: always

volumes:
  config:
    driver: local

networks:
  kibana:
    driver: bridge
