  selfnginx:
    image: jackspanrrows/self_nginx
    container_name: self_nginx
    restart: always
    expose:
     - "80"
    volumes:
     - /private/var/newObject/src/self_project/self_php/github.com:/www/web/self_php
     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
     - selfphp:php
    environment:
     - VIRTUAL_HOST=admin.advertist.com,static.imlaoarc.com,tools.imlaoarc.com,myadmin.imlaoarc.com,admin.youfuysw.com,www.youfurc.com,www.imlaoarc.com

  selfphp:
    image: jackspanrrows/self_php
    container_name: self_php
    expose:
     - "9000"
    restart: always
    volumes:
     - /private/var/newObject/src/self_project/self_php/github.com:/www/web/self_php
     - ./docker/php/src:/usr/local/src
     - ./.ssh:/root/.ssh
     - ./src/php-fpm.conf:/usr/local/etc/php-fpm.conf
     # - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
     #- ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf


