version: '3.0'
services:
  selfnginx:
    image: jackspanrrows/self_nginx:v1.0
    container_name: self_nginx
    restart: always
    expose:
     - "80"
    volumes:
     # - /private/var/newObject/src/self_project/self_php/github.com:/www/web/self_php
     - /Users/pc/newObject/self_project/self_php/github.com:/www/web/self_php
     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
     - self_php:php
    #- go-http-server:http_server
    environment:
     - VIRTUAL_HOST=admin.advertist.com,static.imlaoarc.com

  selfphp:
    image: jackspanrrows/self_php
    container_name: self_php
    expose:
     - "9000"
    restart: always
    volumes:
     - /Users/pc/newObject/self_project/self_php/github.com:/www/web/self_php
     - ./docker/php/src:/usr/local/src
     # - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
     #- ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf


