version: '2'

services:
  master:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
    volumes:
      - ./volume1:/data
  volume:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -port=8080 -ip=volume'
    depends_on:
      - master
    volumes:
      - ./volume2:/data
  filer:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="master:9333"'
    depends_on:
      - master
      - volume
    volumes:
      - ./volume3:/data
  s3:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 8333:8333
    command: 's3 -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
    volumes:
      - ./volume4:/data
  webdav:
    image: chrislusf/seaweedfs:dev # use a remote dev image
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
    volumes:
      - ./volume5:/data