version: '3.0'
services:
  redis:
    image: redis
    container_name: self_redis
    restart: always
    ports:
      - "6366:6379"
    volumes:
      -  ./:/usr/local/src
  mongo:
    image: mongo
    container_name: self_mongo
    ports:
      - '27017:27017'
    volumes:
      - './data:/data'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=rootuser'
      - 'MONGO_INITDB_ROOT_PASSWORD=rootpass'