services:
  redis:
    image: redis
    container_name: self_redis
    restart: always
    ports:
      - "6366:6379"
    volumes:
      -  ./:/usr/local/src
    networks:
      self_network:
        ipv4_address: 172.20.1.7
  mongo:
    image: mongo
    container_name: self_mongo
    ports:
      - '27017:27017'
    volumes:
      - './data:/data'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=rootuser'
      - 'MONGO_INITDB_ROOT_PASSWORD=rootpass'
    networks:
      self_network:
        ipv4_address: 172.20.1.8

networks:
  self_network:
    external: true