version: '3.0'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    container_name: self_node
    restart: unless-stopped
    ports:
       - "17801:17801"
    volumes:
       -  ./:/www
    networks:
       - app-network

networks:
  app-network:
    driver: bridge
