  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
    -  27017:27017
    volumes:
    -  ./src:/usr/local/src

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
     -  6379:6379
    volumes:
     -  ./src:/usr/local/src

  memcached:
    image: memcached
    container_name: memcached
    restart: always
    ports:
     -  11211:11211
    volumes:
     -  ./src:/usr/local/src

