services:
  ubuntu:
    image: jackspanrrows/ubuntu
    container_name: ubuntu
    restart: always
    ports:
      - 80:80
    volumes:
      -  ./:/usr/local/src
      -  /Users/phantom/work/newObject/self_project:/www/web
    networks:
      self_network:
        ipv4_address: 172.20.1.10

networks:
  self_network:
    external: true